# -*- coding: utf-8 -*-
"""LIBRARY MANAGEMENT SYSTEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vPMfop7SLuGym8hwRVPi2nyYoF562Og4
"""

from abc import ABC, abstractmethod
import csv
import os


# -------------------- Abstract Class --------------------
class LibraryItem(ABC):
    @abstractmethod
    def display(self):
        pass


# -------------------- Book Class (Inheritance) --------------------
class Book(LibraryItem):
    def __init__(self, book_id, title, author, status="Available"):
        self.__book_id = book_id
        self.__title = title
        self.__author = author
        self.__status = status

    # Getters
    def get_book_id(self):
        return self.__book_id

    def get_title(self):
        return self.__title

    def get_author(self):
        return self.__author

    def get_status(self):
        return self.__status

    # Setter
    def set_status(self, status):
        self.__status = status

    def display(self):
        print(
            f"ID: {self.__book_id} | "
            f"Title: {self.__title} | "
            f"Author: {self.__author} | "
            f"Status: {self.__status}"
        )


# -------------------- Member Class --------------------
class Member:
    def __init__(self, member_id, name):
        self.__member_id = member_id
        self.__name = name

    def get_member_id(self):
        return self.__member_id

    def get_name(self):
        return self.__name


# -------------------- Library Class --------------------
class Library:
    FILE_NAME = "records.csv"

    def __init__(self):
        self.books = []
        self.load_books()

    # Load books from CSV
    def load_books(self):
        try:
            if os.path.exists(self.FILE_NAME):
                with open(self.FILE_NAME, mode="r", newline="") as file:
                    reader = csv.reader(file)
                    next(reader, None)  # Skip header

                    for row in reader:
                        if len(row) == 4:
                            book = Book(
                                row[0],
                                row[1],
                                row[2],
                                row[3]
                            )
                            self.books.append(book)

        except FileNotFoundError:
            print("records.csv file not found!")

    # Save books to CSV
    def save_books(self):
        with open(self.FILE_NAME, mode="w", newline="") as file:
            writer = csv.writer(file)

            writer.writerow(
                ["Book ID", "Title", "Author", "Status"]
            )

            for book in self.books:
                writer.writerow(
                    [
                        book.get_book_id(),
                        book.get_title(),
                        book.get_author(),
                        book.get_status(),
                    ]
                )

    # Add book
    def add_book(self):
        book_id = input("Enter Book ID: ")
        title = input("Enter Title: ")
        author = input("Enter Author: ")

        book = Book(book_id, title, author)
        self.books.append(book)

        self.save_books()
        print("Book added successfully!\n")

    # Search book
    def search_book(self):
        book_id = input("Enter Book ID to search: ")

        for book in self.books:
            if book.get_book_id() == book_id:
                print("\nBook Found:")
                book.display()
                return

        print("Book not found!\n")

    # Issue book
    def issue_book(self):
        book_id = input("Enter Book ID to issue: ")

        for book in self.books:
            if book.get_book_id() == book_id:
                if book.get_status() == "Available":
                    book.set_status("Issued")
                    self.save_books()
                    print("Book issued successfully!\n")
                else:
                    print("Book is already issued!\n")
                return

        print("Book not found!\n")

    # Return book
    def return_book(self):
        book_id = input("Enter Book ID to return: ")

        for book in self.books:
            if book.get_book_id() == book_id:
                if book.get_status() == "Issued":
                    book.set_status("Available")
                    self.save_books()
                    print("Book returned successfully!\n")
                else:
                    print("Book is already available!\n")
                return

        print("Book not found!\n")

    # Display books
    def display_books(self):
        if len(self.books) == 0:
            print("No books available.\n")
            return

        print("\n------ Available Books ------")
        for book in self.books:
            book.display()
        print()


# -------------------- Main Program --------------------
def main():
    library = Library()

    while True:
        print("===== LIBRARY MANAGEMENT SYSTEM =====")
        print("1. Add Book")
        print("2. Search Book")
        print("3. Issue Book")
        print("4. Return Book")
        print("5. Display Books")
        print("6. Exit")

        try:
            choice = int(input("Enter your choice: "))

            if choice == 1:
                library.add_book()

            elif choice == 2:
                library.search_book()

            elif choice == 3:
                library.issue_book()

            elif choice == 4:
                library.return_book()

            elif choice == 5:
                library.display_books()

            elif choice == 6:
                print("Thank you for using the Library Management System!")
                break

            else:
                print("Please enter a valid choice (1-6).\n")

        except ValueError:
            print("Invalid input! Please enter numbers only.\n")


if __name__ == "__main__":
    main()

import csv

with open("records.csv", "w", newline="") as file:
    writer = csv.writer(file)

    writer.writerow(["Book ID", "Title", "Author", "Status"])

    writer.writerow(["101", "Python Basics", "John Smith", "Available"])
    writer.writerow(["102", "Data Structures", "James Lee", "Issued"])
    writer.writerow(["Machine Learning","ML", "Andrew Ng", "Available"])

print("CSV file created successfully!")

